FROM nginx:1.10
MAINTAINER Robert Watkins

RUN rm /etc/nginx/conf.d/default.conf
RUN rm /etc/nginx/nginx.conf

COPY nginx/jenkins.conf /etc/nginx/conf.d/jenkins.conf
COPY nginx/nginx.conf /etc/nginx/nginx.conf
