version: '2'
services:
  master:
    image: xybersolve/xs-jenkins-blue
    build:
      context: .
      dockerfile: Dockerfile.blueocean
    container_name:  xs-jenkins-blue
    volumes_from:
      - home_data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    networks:
      - jenkins-network

  nginx:
    image: xybersolve/xs-jenkins-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: xs-jenkins-nginx
    environment:
      - HTTP_PORT=${HTTP_PORT}
    ports:
      - "8282:80"
    links:
      - master:jenkins-master
    networks:
      - jenkins-network

  home_data:
    image: busybox
    volumes:
      - jenkins_home

volumes:
  jenkins_home:

networks:
  jenkins-network:
    driver: bridge
  #  external: true

  # docker run \
  #   --name "${JENKINS_CONTAINER}" \
  #   -u root \
  #   --rm \
  #   -d \
  #   -p 8080:8080 \
  #   --volumes-from "${JENKINS_HOME_CONTAINER}" \
  #   -v /var/run/docker.sock:/var/run/docker.sock \
  #   "${JENKINS_IMAGE}"
